###############################
# Ceph Config Map
###############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: ceph-system
data:
  config.json: |-
    [
      {
        "clusterID": "<clusterID>",
        "monitors": [
          "<IP-ADDRESS-1>:6789",
          "<IP-ADDRESS-2>:6789",
          "<IP-ADDRESS-3>:6789"
        ]
      }
    ]



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
  namespace: ceph-system  
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
  # keyring is a required key and its value should be empty
  keyring: |
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-encryption-kms-config
  namespace: ceph-system
data:
  config.json: |-
    {}
