#################################################################
# This is the ceph default storage class for dynamic storage claims
#################################################################
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-coba
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: 32c10e52-758d-11ed-98dc-901b0ebdfb0b
   pool: kubernetes
   imageFeatures: layering
   # The secrets have to contain Ceph credentials with required access
   # to the 'pool'.

#   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret-ceph-coba
#   csi.storage.k8s.io/provisioner-secret-namespace: ceph-system
#   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret-ceph-coba
#   csi.storage.k8s.io/controller-expand-secret-namespace: ceph-system
#   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret-ceph-coba
#   csi.storage.k8s.io/node-stage-secret-namespace: ceph-system

   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret-coba
   csi.storage.k8s.io/provisioner-secret-namespace: ceph-system
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret-coba
   csi.storage.k8s.io/controller-expand-secret-namespace: ceph-system
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret-coba
   csi.storage.k8s.io/node-stage-secret-namespace: ceph-system


   # (optional) Specify the filesystem type of the volume. If not specified,
   # csi-provisioner will set default as `ext4`.
   csi.storage.k8s.io/fstype: ext4
# Note: the reclaimPolicy can be overwritten by a PV
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard

